# Generated by Django 4.0.3 on 2022-09-23 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractorreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Globalid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateissue', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Labourreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('idmark1', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('aadharfile', models.ImageField(null=True, upload_to='')),
                ('color', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('disease', models.CharField(max_length=100)),
                ('sign', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pscode', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('circle', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pscode', models.CharField(max_length=100)),
                ('reqdesc', models.CharField(max_length=100)),
                ('reqdate', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tendercall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('sdate', models.DateField(max_length=100)),
                ('edate', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('conid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.contractorreg')),
                ('reqid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrkamount', models.CharField(max_length=100)),
                ('wsdate', models.CharField(max_length=100)),
                ('wedate', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('tcid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.tendercall')),
            ],
        ),
        migrations.CreateModel(
            name='Worklabors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.globalid')),
                ('wrkid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.workdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Usertypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(max_length=100)),
                ('logid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tender',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.userreg'),
        ),
        migrations.CreateModel(
            name='Labourrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqdate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('conid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.contractorreg')),
                ('lid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.labourreg')),
            ],
        ),
        migrations.AddField(
            model_name='globalid',
            name='labid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.labourreg'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('fdate', models.CharField(max_length=100)),
                ('wid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.workdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('clheight', models.DateField(max_length=100)),
                ('clweight', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('lat', models.DateField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.policestation')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.userreg')),
            ],
        ),
    ]
