# Generated by Django 4.0.3 on 2022-09-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourreg',
            old_name='email',
            new_name='idmark2',
        ),
        migrations.AddField(
            model_name='labourreg',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.policestation'),
        ),
        migrations.AlterField(
            model_name='contractorreg',
            name='certificate',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
