# Generated by Django 4.0.3 on 2022-09-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0002_rename_email_labourreg_idmark2_labourreg_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalid',
            name='dateissue',
            field=models.DateField(auto_now=True),
        ),
    ]
