# Generated by Django 4.0.3 on 2022-09-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0004_labourreg_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='pscode',
        ),
    ]
