# Generated by Django 4.0.3 on 2022-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0006_alter_complaint_clheight_alter_labourrequest_reqdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='lat',
            field=models.CharField(max_length=100),
        ),
    ]
