# Generated by Django 4.0.3 on 2022-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0007_alter_complaint_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
